openapi: 3.0.3
info:
  title: SampleAPI
  description: goa3 sample code.
  version: "1.0"
servers:
- url: http://localhost:8080
paths:
  /api/v1/ha/draw:
    get:
      tags:
      - Ha
      summary: draw card Ha
      description: decied on a theme and card
      operationId: Ha#draw card
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goa3SampleHaCollection'
              example:
              - card: A
                theme: Ha
              - card: A
                theme: Ha
  /api/v1/users:
    get:
      tags:
      - Users
      summary: list user Users
      description: List all stored users
      operationId: Users#list user
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goa3SampleUserCollection'
              example:
              - email: taro.yamada@xxx.jp
                id: XRQ85mtXnINISH25zfM0m5RlC6L2
                name: yamada taro
              - email: taro.yamada@xxx.jp
                id: XRQ85mtXnINISH25zfM0m5RlC6L2
                name: yamada taro
              - email: taro.yamada@xxx.jp
                id: XRQ85mtXnINISH25zfM0m5RlC6L2
                name: yamada taro
              - email: taro.yamada@xxx.jp
                id: XRQ85mtXnINISH25zfM0m5RlC6L2
                name: yamada taro
    post:
      tags:
      - Users
      summary: create user Users
      description: Add new user and return its ID.
      operationId: Users#create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequestBody'
            example:
              email: Eos illum expedita ut doloremque alias distinctio.
              id: XRQ85mtXnINISH25zfM0m5RlC6L2
              name: Corrupti ipsum laborum numquam fugiat.
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                type: string
                example: Nemo ipsa doloribus voluptate qui molestias.
              example: Adipisci esse.
  /api/v1/users/{id}:
    delete:
      tags:
      - Users
      summary: delete user Users
      description: Delete user by id.
      operationId: Users#delete user
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: At facilis quam rerum.
        example: Vitae fugiat dolore dolore ea et.
      responses:
        "204":
          description: No Content response.
    get:
      tags:
      - Users
      summary: get user Users
      description: Show user by ID
      operationId: Users#get user
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: Sunt et officiis odit odit in.
        example: Vel libero optio esse eligendi error voluptas.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goa3SampleUser'
              example:
                email: taro.yamada@xxx.jp
                id: XRQ85mtXnINISH25zfM0m5RlC6L2
                name: yamada taro
    put:
      tags:
      - Users
      summary: update user Users
      description: Update user item.
      operationId: Users#update user
      parameters:
      - name: id
        in: path
        description: User id
        required: true
        schema:
          type: string
          description: User id
          example: XRQ85mtXnINISH25zfM0m5RlC6L2
          minLength: 1
          maxLength: 28
        example: XRQ85mtXnINISH25zfM0m5RlC6L2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequestBody'
            example:
              email: Inventore omnis delectus.
              name: Officia perspiciatis occaecati laboriosam natus autem laborum.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goa3SampleUser'
              example:
                email: taro.yamada@xxx.jp
                id: XRQ85mtXnINISH25zfM0m5RlC6L2
                name: yamada taro
components:
  schemas:
    CreateUserRequestBody:
      type: object
      properties:
        email:
          type: string
          description: Email of user
          example: Dicta fuga.
        id:
          type: string
          description: User id
          example: XRQ85mtXnINISH25zfM0m5RlC6L2
          minLength: 1
          maxLength: 28
        name:
          type: string
          description: Name of user
          example: Quia aut sed ea eum enim natus.
      example:
        email: Sit aspernatur sit officiis earum.
        id: XRQ85mtXnINISH25zfM0m5RlC6L2
        name: Et cupiditate.
      required:
      - id
      - name
      - email
    Goa3SampleHa:
      type: object
      properties:
        card:
          type: string
          description: card of abc
          example: A
        theme:
          type: string
          description: theme of game
          example: Ha
      description: Ha Response
      example:
        card: A
        theme: Ha
      required:
      - theme
      - card
    Goa3SampleHaCollection:
      type: array
      items:
        $ref: '#/components/schemas/Goa3SampleHa'
      example:
      - card: A
        theme: Ha
      - card: A
        theme: Ha
    Goa3SampleUser:
      type: object
      properties:
        email:
          type: string
          description: Email of user
          example: taro.yamada@xxx.jp
        id:
          type: string
          description: User id
          example: XRQ85mtXnINISH25zfM0m5RlC6L2
          minLength: 1
          maxLength: 28
        name:
          type: string
          description: Name of user
          example: yamada taro
      description: User Response
      example:
        email: taro.yamada@xxx.jp
        id: XRQ85mtXnINISH25zfM0m5RlC6L2
        name: yamada taro
      required:
      - id
      - name
      - email
    Goa3SampleUserCollection:
      type: array
      items:
        $ref: '#/components/schemas/Goa3SampleUser'
      example:
      - email: taro.yamada@xxx.jp
        id: XRQ85mtXnINISH25zfM0m5RlC6L2
        name: yamada taro
      - email: taro.yamada@xxx.jp
        id: XRQ85mtXnINISH25zfM0m5RlC6L2
        name: yamada taro
      - email: taro.yamada@xxx.jp
        id: XRQ85mtXnINISH25zfM0m5RlC6L2
        name: yamada taro
      - email: taro.yamada@xxx.jp
        id: XRQ85mtXnINISH25zfM0m5RlC6L2
        name: yamada taro
    UpdateUserRequestBody:
      type: object
      properties:
        email:
          type: string
          description: Email of user
          example: Praesentium autem vitae et autem.
        name:
          type: string
          description: Name of user
          example: Repellat voluptatem.
      example:
        email: Iusto at.
        name: Et occaecati assumenda.
